name: Workflow Runner
on: 
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python 3.9
              uses: actions/setup-python@v3
              with:
                    python-version: '3.9'
            - name: Install dependencies
              run: |
                    python -m pip install --upgrade pip
                    if [ -f requirements.txt ]; then pip install -r workflow/requirements.txt; fi
            - name: Test with pytest
              run: |
                        nosetests --with-coverage --cover-erase --cover-package=. --cover-tests --cover-xml
