name: Workflow Runner
on: 
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
jobs:
    run-test-cases:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                    fetch-depth: 2
            - name: Set up Python 3.9
              uses: actions/setup-python@v3
              with:
                    python-version: '3.9'
            - name: Install dependencies
              run: |
                    echo "$PWD"
                    file=$(git diff --name-only | cut -d'/' -f1 | uniq )
                    IFS=$'\n' read -d "" -r -a services <<< "$file"
                    echo "$PWD"
                    python -m pip install --upgrade pip
                    pip install nose
                    pip install coverage
                    pip install emoji
                    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - name: Test with nosetests
              run: |
                        cd workflow
                        nosetests --with-coverage --cover-erase --cover-package=. --cover-tests --cover-xml
