name: Workflow Runner
on: 
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
jobs:
    run-test-cases:
        permissions:
            contents: read
            issues: read
            checks: write
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                    fetch-depth: 0
            - name: Set up Python 3.9
              uses: actions/setup-python@v3
              with:
                    python-version: '3.9'
            - name: Install dependencies
              run: |
                    python -m pip install --upgrade pip
                    sudo apt-get install libxml2-utils
                    pip install pytest
                    pip install coverage
            - name: Test with nosetests
              run: |
                    file=$(git diff HEAD^..HEAD --name-only | cut -d'/' -f1 | uniq )
                    readarray -t services <<< "$file"
                    echo "${services[@]}"
                    PWD="$(pwd)"
                    TEST_COVERAGE=90
                    for service in "${services[@]}"
                    do
                        case "$service" in
                            "workflow")
                                cd $service
                                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
                                pytest --junitxml=pytest.xml | tee pytest-coverage.txt
                                cd ..
                                ;;
                            "workflow_1")
                                cd $service
                                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
                                pytest --junitxml=pytest.xml | tee pytest-coverage.txt
                                cd ..
                                ;;
                            *)
                                echo "Testcase Action not implemented for {$service}"
                        esac
                    done
            - name: Pytest coverage comment
              uses: xportation/pytest-coverage-comment@main
              with:
                multiple-files: |
                  Workflow -1, ./workflow/pytest-coverage.txt, ./workflow/pytest.xml
                  Workflow -2, ./workflow_1/pytest-coverage.txt, ./workflow_1/pytest.xml
